### ISSUE TITLE
Deprecated API warning

### ISSUE THREAD

**Issue by crowrish** [ukjinjang/react-channel-plugin#47]
### Preview
![image](https://user-images.githubusercontent.com/71705386/168004039-457d0c46-6500-4581-934c-d3f38da7aff4.png)

#### show
> show will be supported until 2022. After that time it will be deprecated.
> NOTE: Recommend to use [showMessenger](https://developers.channel.io/docs/web-channel-io#showmessenger) instead.

https://developers.channel.io/docs/web-channel-io#show

It seems that the deprecated API needs to be changed.

**Comment by crowrish** [comment]
I found out later that marked it in `readme.md` 😰

**Comment by ukjinjang** [comment]
Thanks for let me know @crowrish, and as you said I already marked at README :)

I'll remove them, when finally removed from their SDK.
