### ISSUE TITLE
Possible wrong usages of useRef leads inconsistent behavior of the program

### ISSUE THREAD

**Issue by a3626a** [ukjinjang/react-channel-plugin#64]
### The Problem

Throughout this repository, this pattern repeatly used around.

```typescript
// ...
const someRef = useRef(someProp);

// ... someRef.current is used

useEffect(() => {
  someRef.current = someProp;
}, [someProp]);
```

When we change `someProp` for this component, we expect `someProp` is used and propagated through the component immediately. However using `useRef` and `useEffect` breaks this common expectation. Actually propagation of changed `someProp` requires additional event queue fetching.

This leads several unexpected and inconsistent behavior of the program.

### Actual Issue We Found

One example we found ( and it's the actual reason we wrote this issue ) is the fact that `rebootOnOptionChanged` is not working as expected. (or... it could work in some environment but not guaranteed.)

In [ReactChannelIO.tsx](https://github.com/ukjinjang/react-channel-plugin/blob/master/src/ReactChannelIO.tsx), when `channelIOBootOption` is changed, it triggers re-render of the component and runs several `useEffect` hooks. These are the hooks executed.

The _optionRef Hook_
```typescript
  useEffect(() => {
    optionRef.current = channelIOBootOption;
  }, [channelIOBootOption]);
```

The _reboot hook_
```typescript
  //
  // Re-boot channel plugin when boot option changed.
  //
  useDeepEffect(() => {
    if (isBooted && rebootOnOptionChanged) {
      debugLogger(verbose, 'Rebooting since option has been changed...');
      void boot().catch(() => void 0);
    }
  }, [channelIOBootOption]);
```

For the reboot to work properly with the changed `channelIOBootOption`, _optionRef Hook_ must be executed first which is very hard to guarantee. The actual behavior we faced is that the component reboots Channel IO with old options.

### Suggestion

We think you can safely remove most of `useRef` and just use the passed props directly.

**Comment by ukjinjang** [comment]
Thank you for comment.

I intentionally decided to use this pattern, because I did not intend for these properties to be "reactive values" and not want them directly involved in the render process. 

If you were to remove `useRef`, the `someProp` would need to be included in the dependency array to ensure that it always has the current value. Otherwise, the hook would close over the value of `someProp` at the time of the initial render, and it would not update when `someProp` changes.

But the example you gave could really be a problem, and we might fix it by combining the two hooks you just talked about like:

```tsx
useDeepEffect(() => {
  // update `optionRef` first
  optionRef.current = channelIOBootOption;

  // then reboot, if needed
  if (isBooted && rebootOnOptionChanged) {
    debugLogger(verbose, 'Rebooting since option has been changed...');
    void boot().catch(() => void 0);
  }
}, [channelIOBootOption]);
```

If there are alternative opinion, feel free to share it.

**Comment by a3626a** [comment]
For the first, the code you suggested would solve the problem, Thank you.

----

And More... _(I'm not a React expert. Something I wrote here possibly wrong.)_

When I first read your `useRef` pattern, I think you intended an optimization to reduce number of re-renders, but the optimization actually does not work. (or has no meaning) I think there're no benefits of this pattern.

> I did not intend for these properties to be "reactive values"

I don't get exact point of this...

> not want them directly involved in the render process.

And because `channelIOBootOption` is a component property, they ARE involved in the render process.
I think you intended no renders for changes of `channelIOBootOption` by using `useRef`(or, do I misunderstand your intention?). But there IS a render for every changes of `channelIOBootOption`. Becaues, it is a basic mechanism of React. This does not change if you use `useRef`. `useRef` could reduce renders when its value is originated from outside of React world like user input, DOM element, and so on. Honestly, this is why I started this issue with the title _Possible wrong usage of useRef ..._

Please let me know if I misunderstand your intention or write something wrong.
Thank you.

**Comment by ukjinjang** [comment]
I appreciate your perspective and you make a valid point about React's re-render behavior.

But also my intent with using this pattern is to prevent the `boot()` function from being re-created when options change. If we look at the following example, where I haven't used this pattern and have instead added options as dependencies of `useCallback`, or not used `useCallback` at all, the useEffect hook gets re-triggered whenever boot changes.

```tsx
const { boot } = useChannelIOApi();

React.useEffect(() => {
  boot();
}, [boot])
```

By using `useRef` to hold my options, I'm able to control the re-creation of `boot()` function, which in turn prevents unnecessary re-triggers of the effect hook. This provides an optimization that aligns more effectively with my specific needs for this component.

**Comment by a3626a** [comment]
Thank you for your kind explanation. Now I understand your intention.

Let me add my final opinion as a user of your library

For the tradeoff between _predictable behavior_ vs _rendering performance_ , it seems like you chose rendering performance.

In my use case, properties to `ReactChannelPlugin` rarely changes. First mount, user sign in and sign out. So rendering performance optimization has almost zero value in this case. (it might save less than 10ms during entire user life cycle) On the other hand, omitting user information of ChannelIO has significant business impact*, and debugging, analyzing of this library requires greater cost comparing to optimization benefits.

> \* We rollbacked our new build yesterday because of this.

Anyway, thank you for answering my questions.
