### ISSUE TITLE
It showing some depriciated warnings 

### ISSUE THREAD

**Issue by navneetkumar-pim-webkul** [ukjinjang/react-channel-plugin#65]
Hi There,
I used this plugin with the react its working fine and great but showing following console warnings.

`ch-plugin-core-20230626145524.js:95 Warning: onBoot API is deprecated and will be removed in a future release. Consider using boot callback instead. See https://developers.channel.io/docs/web-channelio#boot for more information.
i @ ch-plugin-core-20230626145524.js:95
ch-plugin-core-20230626145524.js:95 Warning: onShow API is deprecated and will be removed in a future release. Consider using onShowMessenger callback instead. See https://developers.channel.io/docs/web-channelio#onShowMessenger for more information.
i @ ch-plugin-core-20230626145524.js:95
ch-plugin-core-20230626145524.js:95 Warning: onHide API is deprecated and will be removed in a future release. Consider using onHideMessenger callback instead. See https://developers.channel.io/docs/web-channelio#onHideMessenger for more information.
i @ ch-plugin-core-20230626145524.js:95
ch-plugin-core-20230626145524.js:95 Warning: onChangeBadge API is deprecated and will be removed in a future release. Consider using onBadgeChanged callback instead. See https://developers.channel.io/docs/web-channelio#onBadgeChanged for more information.
i @ ch-plugin-core-20230626145524.js:95
ch-plugin-core-20230626145524.js:95 Warning: onCreateChat API is deprecated and will be removed in a future release. Consider using onChatCreated callback instead. See https://developers.channel.io/docs/web-channelio#onChatCreated for more information.
i @ ch-plugin-core-20230626145524.js:95
ch-plugin-core-20230626145524.js:95 Warning: onProfileChanged API is deprecated and will be removed in a future release. Consider using onFollowUpChanged callback instead. See https://developers.channel.io/docs/web-channelio#onFollowUpChanged for more information.
i @ ch-plugin-core-20230626145524.js:95
ch-plugin-core-20230626145524.js:95 Warning: onChangeProfile API is deprecated and will be removed in a future release. Consider using onFollowUpChanged callback instead. See https://developers.channel.io/docs/web-channelio#onFollowUpChanged for more information.
i @ ch-plugin-core-20230626145524.js:95
ch-plugin-core-20230626145524.js:95 Warning: onClickRedirect API is deprecated and will be removed in a future release. Consider using onUrlClicked callback instead. See https://developers.channel.io/docs/web-channelio#onUrlClicked for more information.
i @ ch-plugin-core-20230626145524.js:95
ch-plugin-core-20230626145524.js:95 Warning: onBoot API is deprecated and will be removed in a future release. Consider using boot callback instead. See https://developers.channel.io/docs/web-channelio#boot for more information.
i @ ch-plugin-core-20230626145524.js:95
ch-plugin-core-20230626145524.js:95 Warning: onShow API is deprecated and will be removed in a future release. Consider using onShowMessenger callback instead. See https://developers.channel.io/docs/web-channelio#onShowMessenger for more information.
i @ ch-plugin-core-20230626145524.js:95
ch-plugin-core-20230626145524.js:95 Warning: onHide API is deprecated and will be removed in a future release. Consider using onHideMessenger callback instead. See https://developers.channel.io/docs/web-channelio#onHideMessenger for more information.
i @ ch-plugin-core-20230626145524.js:95
ch-plugin-core-20230626145524.js:95 Warning: onChangeBadge API is deprecated and will be removed in a future release. Consider using onBadgeChanged callback instead. See https://developers.channel.io/docs/web-channelio#onBadgeChanged for more information.
i @ ch-plugin-core-20230626145524.js:95
ch-plugin-core-20230626145524.js:95 Warning: onCreateChat API is deprecated and will be removed in a future release. Consider using onChatCreated callback instead. See https://developers.channel.io/docs/web-channelio#onChatCreated for more information.
i @ ch-plugin-core-20230626145524.js:95
ch-plugin-core-20230626145524.js:95 Warning: onProfileChanged API is deprecated and will be removed in a future release. Consider using onFollowUpChanged callback instead. See https://developers.channel.io/docs/web-channelio#onFollowUpChanged for more information.
i @ ch-plugin-core-20230626145524.js:95
ch-plugin-core-20230626145524.js:95 Warning: onChangeProfile API is deprecated and will be removed in a future release. Consider using onFollowUpChanged callback instead. See https://developers.channel.io/docs/web-channelio#onFollowUpChanged for more information.
i @ ch-plugin-core-20230626145524.js:95
ch-plugin-core-20230626145524.js:95 Warning: onClickRedirect API is deprecated and will be removed in a future release. Consider using onUrlClicked callback instead. See https://developers.channel.io/docs/web-channelio#onUrlClicked for more information.
i @ ch-plugin-core-20230626145524.js:95
ch-plugin-core.4f497a3e.vendor.js:169 WebSocket connection to 'wss://1.front-ws.channel.io/socket.io/?EIO=4&transport=websocket' failed: WebSocket is closed before the connection is established.
doClose @ ch-plugin-core.4f497a3e.vendor.js:169
index.js:63 Array(25)
installHook.js:342 Array(25)
ch-plugin-core-20230626145524.js:95 Warning: onBoot API is deprecated and will be removed in a future release. Consider using boot callback instead. See https://developers.channel.io/docs/web-channelio#boot for more information.
i @ ch-plugin-core-20230626145524.js:95
ch-plugin-core-20230626145524.js:95 Warning: onShow API is deprecated and will be removed in a future release. Consider using onShowMessenger callback instead. See https://developers.channel.io/docs/web-channelio#onShowMessenger for more information.
i @ ch-plugin-core-20230626145524.js:95
ch-plugin-core-20230626145524.js:95 Warning: onHide API is deprecated and will be removed in a future release. Consider using onHideMessenger callback instead. See https://developers.channel.io/docs/web-channelio#onHideMessenger for more information.
i @ ch-plugin-core-20230626145524.js:95
ch-plugin-core-20230626145524.js:95 Warning: onChangeBadge API is deprecated and will be removed in a future release. Consider using onBadgeChanged callback instead. See https://developers.channel.io/docs/web-channelio#onBadgeChanged for more information.
i @ ch-plugin-core-20230626145524.js:95
ch-plugin-core-20230626145524.js:95 Warning: onCreateChat API is deprecated and will be removed in a future release. Consider using onChatCreated callback instead. See https://developers.channel.io/docs/web-channelio#onChatCreated for more information.
i @ ch-plugin-core-20230626145524.js:95
ch-plugin-core-20230626145524.js:95 Warning: onProfileChanged API is deprecated and will be removed in a future release. Consider using onFollowUpChanged callback instead. See https://developers.channel.io/docs/web-channelio#onFollowUpChanged for more information.
i @ ch-plugin-core-20230626145524.js:95
ch-plugin-core-20230626145524.js:95 Warning: onChangeProfile API is deprecated and will be removed in a future release. Consider using onFollowUpChanged callback instead. See https://developers.channel.io/docs/web-channelio#onFollowUpChanged for more information.
i @ ch-plugin-core-20230626145524.js:95
ch-plugin-core-20230626145524.js:95 Warning: onClickRedirect API is deprecated and will be removed in a future release. Consider using onUrlClicked callback instead. See https://developers.channel.io/docs/web-channelio#onUrlClicked for more information.`

**Comment by ukjinjang** [comment]
Thanks for your comment!

The issue duplicated with https://github.com/ukjinjang/react-channel-plugin/issues/47, and please let me know if any further questions.

**Comment by synuns** [comment]
Did you quit maintenance?

**Comment by ukjinjang** [comment]
I just released a new version, [3.0.0-rc.0](https://github.com/ukjinjang/react-channel-plugin/releases/tag/v3.0.0-rc.0).
Please check out the newer version and let me know if there are any issues.
